'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs/promises'),path=require('node:path'),os=require('node:os');
const {readLedger,atomicLedger}=require('../src/json-store'),{MetadataPool}=require('../src/metadata-pool');
const {fixture,claudeRow,TIME}=require('./helpers'),{Collector}=require('../src/collector'),{UsageLog,fingerprint,SCHEMA}=require('../src/usage-log');
const {ViewCache}=require('../src/view-cache'),{byteLines}=require('../src/byte-lines'),{Readable}=require('node:stream');
async function temporary(t){const dir=await fs.mkdtemp(path.join(os.tmpdir(),'tm-stream-test-'));t.after(()=>fs.rm(dir,{recursive:true,force:true}));return dir;}
for(const chunk of [1,2,7,65,65536])test(`Streaming ledger parses nested/escaped Unicode at ${chunk}-byte boundaries`,async t=>{
 const dir=await temporary(t),file=path.join(dir,'ledger.json');const data={version:2,events:[{id:'a',name:'한글\\"😀\n',nested:[{z:3},true,null]},{id:'b',s:'},]["'}],files:{c:{state:{a:'x'}}},sourceEvents:[{id:'s',values:[1,2,-1.4,0.5]}],resetBoundary:{baseline:[['x',{in:33}]]}};
 await atomicLedger(file,data);assert.deepEqual(await readLedger(file,undefined,{highWaterMark:chunk}),data);
});
for(const text of ['{','{"events":[{"id":"a"}', '{"events":[],}', '{"events":[{},]}', '{"events":[],"events":[]}', '{"events":[]}junk','{"events":notarray}','[{}]'])test('Damaged streaming ledger fails closed: '+text,async t=>{
 const dir=await temporary(t),file=path.join(dir,'ledger.json');await fs.writeFile(file,text);await assert.rejects(()=>readLedger(file),/ledger.json/);assert.equal(await fs.readFile(file,'utf8'),text);
});
test('Missing ledger returns null, not an empty fabricated data set',async t=>{const d=await temporary(t);assert.equal(await readLedger(path.join(d,'absent.json')),null);});
test('Atomic streaming writer failure leaves prior file intact and removes temp output',async t=>{const d=await temporary(t),p=path.join(d,'ledger.json');await atomicLedger(p,{version:1});await assert.rejects(()=>atomicLedger(p,{events:[{x:1n}]}));assert.deepEqual(JSON.parse(await fs.readFile(p)),{version:1});assert.deepEqual(await fs.readdir(d),['ledger.json']);});
test('Immutable metadata pool shares ONLY identical rates and is bounded',()=>{const p=new MetadataPool(3),rate={models:['a'],input:2,baseRule:{models:['a'],input:2}},a=p.intern(rate),b=p.intern(structuredClone(rate)),c=p.intern({...rate,input:3});assert.equal(a,b);assert.notEqual(a,c);assert.throws(()=>{a.baseRule.input=9});for(let i=0;i<20;i++)p.intern({models:['m'+i]});assert.equal(p.stats().entries,3);});
test('Journal collector index has no retained event graph and does not reimport on restart',async t=>{const f=await fixture(t);await f.write('claude','one.jsonl',[claudeRow()]);await f.c.scan();const r=[...f.c.journal.latest.values()][0];assert.equal(r.event,undefined);assert.ok(r.fingerprint);const seq=f.c.journal.sequence;const c=await new Collector(f.data).init();await c.scan();assert.equal(c.journal.sequence,seq);assert.equal(c.events.size,1);});
test('Compact replay preserves highest sequence even if month files arrive out of order',async t=>{const f=await fixture(t);await f.write('claude','one.jsonl',[claudeRow()]);await f.c.scan();const safe=require('../src/usage-log').safeEvent([...f.c.events.values()][0]),dir=await temporary(t),folder=path.join(dir,'usage-log');await fs.mkdir(folder);
 const newer={...safe,output:safe.output+5,total:safe.total+5};for(const [name,seq,e] of [['2026-01',3,newer],['2026-02',2,safe]])await fs.writeFile(path.join(folder,name+'.jsonl'),JSON.stringify({schema:SCHEMA,seq,revision:seq,id:e.id,event:e,fingerprint:fingerprint(e),observedAt:TIME})+'\n');
 let last;const log=await new UsageLog(dir,{compact:true}).init({afterSequence:0,onRecord:r=>{last=r.event;}});assert.equal(last.output,newer.output);assert.equal(log.latest.get(safe.id).seq,3);
});
test('ViewCache is bounded, expires and never reuses a different key',()=>{let n=0;const c=new ViewCache({limit:2,maxBytes:100,ttl:50});const first=c.get('a',()=>({x:++n}),0);assert.equal(c.get('a',()=>({x:++n}),20),first);c.get('b',()=>({x:++n}),25);c.get('c',()=>({x:++n}),30);assert.equal(c.stats().entries,2);assert.notEqual(c.get('a',()=>({x:++n}),200),first);assert.ok(c.bytes<=100);});
test('Byte line reader handles large fragmented lines and incomplete tails without concat loops',async()=>{const expected=Buffer.alloc(2*1024*1024,97),all=Buffer.concat([expected,Buffer.from('\nsmall\ntail')]);const chunks=[];for(let i=0;i<all.length;i+=4093)chunks.push(all.subarray(i,i+4093));const rows=[];for await(const r of byteLines(Readable.from(chunks)))rows.push(r);assert.equal(rows.length,3);assert.deepEqual(rows[0].line,expected);assert.equal(rows[1].line.toString(),'small');assert.equal(rows[2].complete,false);});
test('Byte reader enforces size cap before a complete line is allocated',async()=>{await assert.rejects(async()=>{for await(const _ of byteLines(Readable.from([Buffer.alloc(50),Buffer.alloc(50)]),{maxBytes:60})){};},/limit/);});
test('Streaming CSV and JSONL preserve byte-for-byte public export compatibility',async t=>{const f=await fixture(t);await f.write('claude','many.jsonl',Array.from({length:300},(_,i)=>claudeRow({id:'n'+i})));await f.c.scan();const h=require('../src/history');for(const format of ['csv','jsonl'])assert.equal([...h.historyChunks(f.c,{},format)].join(''),h.exportHistory(f.c,{},format));const rows=[...h.historyChunks(f.c,{},'jsonl')].map(s=>JSON.parse(s));assert.equal(rows.length,300);assert.equal(new Set(rows.map(r=>r.id)).size,300);});
test('Statusbar summary avoids unused history/group payloads without changing totals',async t=>{const f=await fixture(t);await f.write('claude','rows.jsonl',[claudeRow(),claudeRow({id:'r2'})]);await f.c.scan();const {summarize,statusLine}=require('../src/summary');const full=summarize(f.c,{scope:'all'}),lean=summarize(f.c,{scope:'all',view:'statusbar'});assert.deepEqual(lean.summary,full.summary);assert.equal(lean.recent.length,0);assert.equal(lean.byModel.length,0);assert.equal(statusLine(lean),statusLine(full));});
test('Unchanged reset source observations do not create new journal revisions or writes',async t=>{
 const f=await fixture(t);await f.write('claude','rows.jsonl',[claudeRow()]);await f.c.scan();const {Measurements}=require('../src/measurements');await new Measurements(f.c).init();await f.c.resetAll({confirmation:'전체 초기화',requestKey:require('node:crypto').randomUUID(),expectedEpochId:'legacy'});
 const raw=[...f.c.sourceEvents.values()][0];f.c.dirty=false;f.c.insert(structuredClone(raw));assert.equal(f.c.dirty,false);assert.equal(f.c.events.size,0);
});
test('Accounting metadata survives reset baseline and compact journal restoration',async t=>{
 const f=await fixture(t),{database,generation}=require('./antigravity-fixtures');database(f.file('antigravity','account.db'),[generation()]);await f.c.scan();const e=[...f.c.events.values()][0];const safe=require('../src/usage-log').safeEvent(e);assert.equal(safe.accountingVersion,2);assert.equal(safe.usageSourceKind,e.usageSourceKind);assert.equal(safe.usageObservedAt,e.usageObservedAt);
});
test('Concurrent queued saves retain latest coherent ledger with immutable prices',async t=>{const f=await fixture(t);await f.write('claude','rows.jsonl',[claudeRow()]);await f.c.scan();const jobs=[];for(let i=0;i<10;i++){f.c.tasks.push({id:String(i),start:TIME,end:TIME});jobs.push(f.c.save());}await Promise.all(jobs);const ledger=await readLedger(path.join(f.data,'ledger.json'));assert.equal(ledger.tasks.length,10);assert.equal(ledger.events.length,1);assert.equal(f.c.pendingSaves,0);});
test('Legacy collector without ping is recognized for normal versioned upgrade',async()=>{const calls=[],{probe}=require('../src/client');const result=await probe('/fake',async(_d,url)=>{calls.push(url);if(url==='/api/ping')throw Object.assign(new Error('old collector'),{status:404});return {version:'0.10.1'};});assert.equal(result.version,'0.10.1');assert.deepEqual(calls,['/api/ping','/api/status?scope=all&view=statusbar']);});
test('Probe never falls back to costly summary when authentication or transport fails',async()=>{let n=0;const {probe}=require('../src/client');await assert.rejects(()=>probe('/fake',async()=>{n++;throw Object.assign(new Error('unauthorized'),{status:401});}));assert.equal(n,1);});
test('General CSV/JSON stream preserves format, empty rows and all metadata',async t=>{const f=await fixture(t),s=require('../src/summary');assert.equal([...s.exportCsvChunks(f.c,{scope:'all'})].join(''),s.exportCsv(f.c,{scope:'all'}));await f.write('claude','rows.jsonl',[claudeRow(),claudeRow({id:'b'})]);await f.c.scan();assert.equal([...s.exportCsvChunks(f.c,{scope:'all'})].join(''),s.exportCsv(f.c,{scope:'all'}));assert.deepEqual(JSON.parse([...s.exportJsonChunks(f.c,{scope:'all'})].join('')).events,[...f.c.events.values()]);});
test('HTTP performance endpoint is private; cached status invalidates on ingest and reset',async t=>{const f=await fixture(t);await f.write('claude','rows.jsonl',[claudeRow()]);const a=await require('../src/server').startServer({dataDir:f.data});t.after(()=>a.close());const get=p=>fetch(a.runtime.origin+p,{headers:{Authorization:'Bearer '+a.runtime.token}}),post=(p,v)=>fetch(a.runtime.origin+p,{method:'POST',headers:{Authorization:'Bearer '+a.runtime.token},body:JSON.stringify(v)});
 assert.equal((await fetch(a.runtime.origin+'/api/performance')).status,401);assert.equal((await fetch(a.runtime.origin+'/api/ping')).status,401);assert.equal((await (await get('/api/ping')).json()).version,require('../package.json').version);
 for(let i=0;i<5;i++)assert.equal((await (await get('/api/status?scope=all&view=statusbar')).json()).summary.records,1);const perf=await (await get('/api/performance')).json();assert.ok(perf.viewCache.hits>=4);assert.ok(perf.rssBytes>0);assert.ok(!JSON.stringify(perf).includes(a.runtime.token));
 const e={schema:'token-meter.usage.v1',format:'normalized',modelProvider:'openai',model:'gpt-6-sol',requestId:'new',timestamp:new Date().toISOString(),modality:'text',usage:{input:1000,cacheRead:0,cacheWriteUnknown:0,output:100,thinkingOutput:50}};assert.equal((await post('/api/usage',e)).status,200);const d=await (await get('/api/status?scope=all&view=statusbar')).json();assert.equal(d.summary.records,2);assert.equal(d.summary.total,1265);
 const state=await (await get('/api/data/state')).json();assert.equal((await post('/api/data/reset',{expectedEpochId:state.epochId,requestKey:require('node:crypto').randomUUID(),confirmation:'전체 초기화'})).status,200);assert.equal((await (await get('/api/status?scope=all&view=statusbar')).json()).summary.total,0);
});
test('Unchanged partial DB reuses bounded snapshot but retains warning and explicit reanalysis',async t=>{const f=await fixture(t),{database,generation}=require('./antigravity-fixtures');database(f.file('antigravity','partial.db'),[generation(),Buffer.from([255])]);await f.c.scan();assert.ok(f.c.health.antigravity.partial);const key='antigravity:'+f.file('antigravity','partial.db'),before=f.c.files[key];await f.c.scan();assert.ok(f.c.health.antigravity.partial);assert.equal(f.c.files[key],before);await f.c.reanalyseAntigravity();assert.ok(f.c.health.antigravity.partial);assert.notEqual(f.c.files[key],before);});
test('Cached token totals do not cache a stale Antigravity health error',async t=>{const f=await fixture(t);const a=await require('../src/server').startServer({dataDir:f.data});t.after(()=>a.close());const get=async p=>{const r=await fetch(a.runtime.origin+p,{headers:{Authorization:'Bearer '+a.runtime.token}});assert.equal(r.status,200);return r.json();};await get('/api/status?scope=all');a.collector.health.antigravity={errors:1,partial:true,status:'partial'};let d=await get('/api/status?scope=all');assert.equal(d.health.antigravity.errors,1);assert.equal(d.antigravity.health.status,'partial');a.collector.health.antigravity={errors:0,partial:false,status:'observed'};d=await get('/api/status?scope=all');assert.equal(d.antigravity.health.status,'observed');});
test('Malformed streamed export selection is a JSON HTTP 400, not a partial successful download',async t=>{const f=await fixture(t);const a=await require('../src/server').startServer({dataDir:f.data});t.after(()=>a.close());for(const p of ['/api/history/export.csv?priceStatus=not-a-status','/api/history/export.jsonl?from=broken','/api/export.csv?scope=bad','/api/export.json?scope=bad']){const r=await fetch(a.runtime.origin+p,{headers:{Authorization:'Bearer '+a.runtime.token}});assert.equal(r.status,400);assert.ok((await r.json()).error);}});
test('Stable DB signature never bypasses a required accounting migration',async t=>{const f=await fixture(t),{database,generation}=require('./antigravity-fixtures');const file=f.file('antigravity','needs-repair.db');database(file,[generation()]);await f.c.scan();const old=f.c.files['antigravity:'+file],e=[...f.c.events.values()][0],total=e.total;delete e.accountingVersion;old.partial=true;await f.c.scan();assert.notEqual(f.c.files['antigravity:'+file],old);assert.equal([...f.c.events.values()][0].accountingVersion,2);assert.equal([...f.c.events.values()][0].total,total);assert.equal(f.c.health.antigravity.unrepairedAccountingRecords,0);assert.equal(f.c.events.size,1);});
test('Legacy version probe authenticates a tiny config response rather than a full history',async()=>{const calls=[],{probe}=require('../src/client');const r=await probe('/fake',async(_d,url)=>{calls.push(url);if(url==='/api/ping')throw Object.assign(new Error('missing'),{status:404});return {};},async()=>({appVersion:'0.10.1'}));assert.equal(r.version,'0.10.1');assert.deepEqual(calls,['/api/ping','/api/config']);});
test('Shared rate display cache cannot reuse a valid binding across an expired or missing timestamp',async t=>{const f=await fixture(t);await f.write('claude','dated.jsonl',[claudeRow()]);await f.c.scan();const a=structuredClone([...f.c.events.values()][0]);a.price.rate.baseRule.effectiveFrom='2026-01-01T00:00:00Z';a.price.rate.baseRule.effectiveTo='2027-01-01T00:00:00Z';new MetadataPool().event(a);const x=require('../src/input-breakdown'),map=x.blankRates();x.addRate(map,a);x.addRate(map,{...a,timestamp:'2027-02-01T00:00:00Z'});x.addRate(map,{...a,timestamp:null});const groups=x.finishRates(map);assert.equal(groups.length,2);assert.equal(groups.find(x=>x.available).records,1);assert.equal(groups.find(x=>!x.available).records,2);assert.ok(groups.find(x=>!x.available).binding.reasonCodes.includes('date-mismatch'));});
